#название билда
name: Java CI with Gradle

#какие события его триггерят, в какие ветки
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#Джобы. Их может быть несколько
jobs:
  build:
#на чём запускается. опция ниже — басплатная для опенсорса
    runs-on: ubuntu-latest
    permissions:
      contents: read

#uses как плагины
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - run: ./gradlew clean test